[package]
name = "helium-wallet"
version = "1.3.11"
authors = ["Helium <info@helium.com>"]
edition = "2018"
build = "build.rs"

description = "A Rust Helium Wallet library"
readme = "README.md"
keywords = ["helium", "blockchain", "wallet"]

homepage = "https://developer.helium.com/blockchain/blockchain-cli"
repository = "https://github.com/helium/helium-wallet-rs"

license = "Apache-2.0"

[[bin]]
name = "helium-wallet"
path = "src/main.rs"
doc = false

[dependencies]
byteorder = "1.3.2"
structopt = "0.3"
dialoguer = "0.6"
console = "0.11"
bs58 = {version = "0.3.0", features=["check"]}
sodiumoxide = "0.2.5"
hex = "0.4.2"
hmac = "0.7.1"
sha2 = "0.8.0"
base64 = "0"
reqwest = "0.11.1"
bytes = "0"
pbkdf2 = {version = "0.3.0", default-features=false }
aead = "0.1.1"
aes-gcm = "0.1.0"
lazy_static = "1"
regex = "1"
qr2term = "0.1"
serde =  "1"
serde_derive = "1"
serde_json = "1"
rust_decimal = {version = "1", features = ["serde-float"] }
helium-api = { git = "https://github.com/helium/helium-api-rs", tag="v1.1.7" }


# Add openssl-sys as a direct dependency so it can be cross compiled to
# x86_64-unknown-linux-musl using the "vendored" feature below
openssl-sys = "*"

[features]
# Force openssl-sys to staticly link in the openssl library. Necessary when
# cross compiling to x86_64-unknown-linux-musl.
vendored = ["openssl-sys/vendored"]
